export interface FilterIcon {
  value: string;
  label: string;
  category: string;
  searchTerms: ReadonlyArray<string>;
}

export const FILTER_ICON_CATEGORIES: ReadonlyArray<string> = [
  "Featured",
  "Status",
  "Code",
  "Tools",
  "People",
  "Objects",
  "Symbols",
  "Nature",
  "Activity"
];

export const FILTER_ICONS: ReadonlyArray<FilterIcon> = [
  { value: "🐛", label: "Bug", category: "Featured", searchTerms: ["bug", "issue", "defect", "insect"] },
  { value: "✨", label: "Feature", category: "Featured", searchTerms: ["feature", "sparkles", "new", "shiny"] },
  { value: "🔧", label: "Fix", category: "Featured", searchTerms: ["fix", "wrench", "repair", "tool"] },
  { value: "🧹", label: "Chore", category: "Featured", searchTerms: ["chore", "broom", "cleanup", "tidy"] },
  { value: "📝", label: "Docs", category: "Featured", searchTerms: ["docs", "documentation", "memo", "notes"] },
  { value: "🧪", label: "Tests", category: "Featured", searchTerms: ["test", "tests", "experiment", "lab"] },
  { value: "🎨", label: "Style", category: "Featured", searchTerms: ["style", "design", "art", "ui"] },
  { value: "🚧", label: "WIP", category: "Featured", searchTerms: ["wip", "construction", "progress", "draft"] },
  { value: "🔥", label: "Hot", category: "Featured", searchTerms: ["hot", "fire", "urgent", "hotfix"] },
  { value: "⚡", label: "Performance", category: "Featured", searchTerms: ["performance", "perf", "fast", "speed", "lightning"] },
  { value: "🛡️", label: "Security", category: "Featured", searchTerms: ["security", "shield", "protect", "safe"] },
  { value: "👀", label: "Review", category: "Featured", searchTerms: ["review", "eyes", "watch", "look"] },
  { value: "🚀", label: "Release", category: "Featured", searchTerms: ["release", "rocket", "ship", "launch"] },
  { value: "🎯", label: "Milestone", category: "Featured", searchTerms: ["milestone", "target", "goal", "aim"] },
  { value: "🤖", label: "Bot", category: "Featured", searchTerms: ["bot", "robot", "automation", "ci"] },
  { value: "👤", label: "Me", category: "Featured", searchTerms: ["me", "user", "person", "profile"] },
  { value: "📦", label: "Package", category: "Featured", searchTerms: ["package", "box", "deps", "dependency"] },
  { value: "🌐", label: "Web", category: "Featured", searchTerms: ["web", "globe", "internet", "network"] },
  { value: "📱", label: "Mobile", category: "Featured", searchTerms: ["mobile", "phone", "app", "device"] },
  { value: "💾", label: "Data", category: "Featured", searchTerms: ["data", "save", "disk", "storage"] },
  { value: "🔐", label: "Auth", category: "Featured", searchTerms: ["auth", "lock", "login", "password"] },
  { value: "🧱", label: "Infra", category: "Featured", searchTerms: ["infra", "infrastructure", "brick", "platform"] },
  { value: "📊", label: "Metrics", category: "Featured", searchTerms: ["metrics", "chart", "stats", "analytics"] },
  { value: "🏷️", label: "Label", category: "Featured", searchTerms: ["label", "tag", "category"] },

  { value: "✅", label: "Check", category: "Status", searchTerms: ["check", "done", "ok", "pass", "success"] },
  { value: "❌", label: "Cross", category: "Status", searchTerms: ["cross", "fail", "no", "wrong", "error"] },
  { value: "⚠️", label: "Warning", category: "Status", searchTerms: ["warning", "warn", "caution", "alert"] },
  { value: "🚫", label: "Blocked", category: "Status", searchTerms: ["blocked", "no", "stop", "prohibited"] },
  { value: "⏳", label: "Waiting", category: "Status", searchTerms: ["waiting", "hourglass", "pending", "time"] },
  { value: "⏰", label: "Deadline", category: "Status", searchTerms: ["deadline", "alarm", "clock", "time"] },
  { value: "🆕", label: "New", category: "Status", searchTerms: ["new", "fresh", "added"] },
  { value: "🔁", label: "Repeat", category: "Status", searchTerms: ["repeat", "retry", "loop", "again"] },
  { value: "🆗", label: "OK", category: "Status", searchTerms: ["ok", "fine", "approved"] },
  { value: "🔝", label: "Top", category: "Status", searchTerms: ["top", "priority", "high"] },
  { value: "💯", label: "Done", category: "Status", searchTerms: ["done", "perfect", "hundred", "complete"] },
  { value: "🟢", label: "Green", category: "Status", searchTerms: ["green", "go", "ok", "healthy"] },
  { value: "🟡", label: "Yellow", category: "Status", searchTerms: ["yellow", "warning", "caution"] },
  { value: "🔴", label: "Red", category: "Status", searchTerms: ["red", "stop", "danger", "broken"] },
  { value: "🟣", label: "Purple", category: "Status", searchTerms: ["purple"] },
  { value: "🟠", label: "Orange", category: "Status", searchTerms: ["orange"] },
  { value: "🔵", label: "Blue", category: "Status", searchTerms: ["blue"] },

  { value: "💻", label: "Laptop", category: "Code", searchTerms: ["laptop", "computer", "code", "dev"] },
  { value: "🖥️", label: "Desktop", category: "Code", searchTerms: ["desktop", "monitor", "screen", "computer"] },
  { value: "⌨️", label: "Keyboard", category: "Code", searchTerms: ["keyboard", "type"] },
  { value: "🖱️", label: "Mouse", category: "Code", searchTerms: ["mouse", "click"] },
  { value: "💿", label: "Disc", category: "Code", searchTerms: ["disc", "cd", "build"] },
  { value: "📀", label: "DVD", category: "Code", searchTerms: ["dvd", "disc"] },
  { value: "🗄️", label: "Archive", category: "Code", searchTerms: ["archive", "files", "cabinet"] },
  { value: "🗃️", label: "Files", category: "Code", searchTerms: ["files", "card", "box"] },
  { value: "📁", label: "Folder", category: "Code", searchTerms: ["folder", "directory"] },
  { value: "📂", label: "Open folder", category: "Code", searchTerms: ["folder", "open"] },
  { value: "📄", label: "Document", category: "Code", searchTerms: ["document", "file", "page"] },
  { value: "📃", label: "Scroll page", category: "Code", searchTerms: ["page", "scroll", "document"] },
  { value: "🧾", label: "Receipt", category: "Code", searchTerms: ["receipt", "log", "record"] },
  { value: "🗂️", label: "Dividers", category: "Code", searchTerms: ["dividers", "tabs", "organize"] },
  { value: "🪲", label: "Beetle", category: "Code", searchTerms: ["beetle", "bug"] },
  { value: "🦠", label: "Virus", category: "Code", searchTerms: ["virus", "microbe", "regression"] },
  { value: "🔬", label: "Microscope", category: "Code", searchTerms: ["microscope", "research", "investigate"] },
  { value: "🧬", label: "DNA", category: "Code", searchTerms: ["dna", "genetics", "core"] },
  { value: "📡", label: "Antenna", category: "Code", searchTerms: ["antenna", "satellite", "broadcast", "api"] },
  { value: "🛰️", label: "Satellite", category: "Code", searchTerms: ["satellite", "orbit", "service"] },
  { value: "🧮", label: "Abacus", category: "Code", searchTerms: ["abacus", "compute", "math"] },
  { value: "🪟", label: "Window", category: "Code", searchTerms: ["window", "ui", "view"] },
  { value: "🖲️", label: "Trackball", category: "Code", searchTerms: ["trackball", "input"] },

  { value: "🛠️", label: "Hammer & wrench", category: "Tools", searchTerms: ["tools", "hammer", "wrench", "build"] },
  { value: "🔨", label: "Hammer", category: "Tools", searchTerms: ["hammer", "build", "construct"] },
  { value: "🪓", label: "Axe", category: "Tools", searchTerms: ["axe", "chop"] },
  { value: "⛏️", label: "Pick", category: "Tools", searchTerms: ["pick", "mining"] },
  { value: "⚙️", label: "Gear", category: "Tools", searchTerms: ["gear", "settings", "config", "cog"] },
  { value: "🔩", label: "Bolt", category: "Tools", searchTerms: ["bolt", "screw", "hardware"] },
  { value: "🧰", label: "Toolbox", category: "Tools", searchTerms: ["toolbox", "tools", "kit"] },
  { value: "🧲", label: "Magnet", category: "Tools", searchTerms: ["magnet", "attract"] },
  { value: "🪛", label: "Screwdriver", category: "Tools", searchTerms: ["screwdriver", "tool"] },
  { value: "🪚", label: "Saw", category: "Tools", searchTerms: ["saw", "cut"] },
  { value: "📐", label: "Ruler triangle", category: "Tools", searchTerms: ["ruler", "triangle", "measure"] },
  { value: "📏", label: "Ruler", category: "Tools", searchTerms: ["ruler", "measure"] },
  { value: "🧷", label: "Pin", category: "Tools", searchTerms: ["pin", "safety pin", "attach"] },
  { value: "📌", label: "Pushpin", category: "Tools", searchTerms: ["pushpin", "pin", "pinned"] },
  { value: "📍", label: "Location pin", category: "Tools", searchTerms: ["location", "pin", "place"] },
  { value: "🔍", label: "Search", category: "Tools", searchTerms: ["search", "find", "magnifier", "look"] },
  { value: "🔎", label: "Search right", category: "Tools", searchTerms: ["search", "find", "magnifier"] },
  { value: "🔑", label: "Key", category: "Tools", searchTerms: ["key", "auth", "secret"] },
  { value: "🗝️", label: "Old key", category: "Tools", searchTerms: ["key", "old", "legacy"] },
  { value: "🔒", label: "Lock", category: "Tools", searchTerms: ["lock", "private", "secure"] },
  { value: "🔓", label: "Unlock", category: "Tools", searchTerms: ["unlock", "open", "public"] },
  { value: "🔔", label: "Bell", category: "Tools", searchTerms: ["bell", "notification", "alert"] },
  { value: "🔕", label: "Mute", category: "Tools", searchTerms: ["mute", "silent", "quiet"] },
  { value: "📣", label: "Megaphone", category: "Tools", searchTerms: ["megaphone", "announce"] },
  { value: "📢", label: "Loudspeaker", category: "Tools", searchTerms: ["loud", "speaker", "broadcast"] },

  { value: "👩", label: "Woman", category: "People", searchTerms: ["woman", "person"] },
  { value: "👨", label: "Man", category: "People", searchTerms: ["man", "person"] },
  { value: "🧑", label: "Person", category: "People", searchTerms: ["person", "user"] },
  { value: "👥", label: "Team", category: "People", searchTerms: ["team", "people", "group", "users"] },
  { value: "👶", label: "Baby", category: "People", searchTerms: ["baby", "new"] },
  { value: "🧙", label: "Mage", category: "People", searchTerms: ["mage", "wizard", "magic"] },
  { value: "🧑‍💻", label: "Developer", category: "People", searchTerms: ["developer", "coder", "tech"] },
  { value: "🧑‍🔧", label: "Mechanic", category: "People", searchTerms: ["mechanic", "fix"] },
  { value: "🧑‍🚀", label: "Astronaut", category: "People", searchTerms: ["astronaut", "space"] },
  { value: "🧑‍🎨", label: "Artist", category: "People", searchTerms: ["artist", "design"] },
  { value: "🧑‍🏫", label: "Teacher", category: "People", searchTerms: ["teacher", "instructor"] },
  { value: "👮", label: "Officer", category: "People", searchTerms: ["officer", "police", "guard"] },
  { value: "🦸", label: "Hero", category: "People", searchTerms: ["hero", "superhero"] },
  { value: "🤝", label: "Handshake", category: "People", searchTerms: ["handshake", "deal", "agree"] },
  { value: "👋", label: "Wave", category: "People", searchTerms: ["wave", "hello", "hi"] },
  { value: "👍", label: "Thumbs up", category: "People", searchTerms: ["thumbs up", "approve", "ok"] },
  { value: "👎", label: "Thumbs down", category: "People", searchTerms: ["thumbs down", "reject"] },
  { value: "🙏", label: "Please", category: "People", searchTerms: ["please", "pray", "thanks"] },
  { value: "💪", label: "Strong", category: "People", searchTerms: ["strong", "muscle", "power"] },
  { value: "🧠", label: "Brain", category: "People", searchTerms: ["brain", "smart", "think", "ai"] },

  { value: "📚", label: "Books", category: "Objects", searchTerms: ["books", "library", "docs"] },
  { value: "📖", label: "Book", category: "Objects", searchTerms: ["book", "read", "docs"] },
  { value: "📓", label: "Notebook", category: "Objects", searchTerms: ["notebook", "notes"] },
  { value: "📒", label: "Ledger", category: "Objects", searchTerms: ["ledger", "notebook"] },
  { value: "📔", label: "Journal", category: "Objects", searchTerms: ["journal", "diary"] },
  { value: "📰", label: "News", category: "Objects", searchTerms: ["news", "newspaper", "feed"] },
  { value: "📅", label: "Calendar", category: "Objects", searchTerms: ["calendar", "date", "schedule"] },
  { value: "📆", label: "Tear-off cal", category: "Objects", searchTerms: ["calendar", "date"] },
  { value: "🗓️", label: "Spiral cal", category: "Objects", searchTerms: ["calendar", "schedule"] },
  { value: "📈", label: "Chart up", category: "Objects", searchTerms: ["chart", "up", "growth", "metrics"] },
  { value: "📉", label: "Chart down", category: "Objects", searchTerms: ["chart", "down", "decline"] },
  { value: "📋", label: "Clipboard", category: "Objects", searchTerms: ["clipboard", "tasks", "list"] },
  { value: "📇", label: "Card index", category: "Objects", searchTerms: ["card", "index", "rolodex"] },
  { value: "💼", label: "Briefcase", category: "Objects", searchTerms: ["briefcase", "work", "business"] },
  { value: "🗳️", label: "Ballot box", category: "Objects", searchTerms: ["ballot", "vote", "poll"] },
  { value: "💡", label: "Idea", category: "Objects", searchTerms: ["idea", "lightbulb", "insight"] },
  { value: "🔋", label: "Battery", category: "Objects", searchTerms: ["battery", "power"] },
  { value: "🔌", label: "Plug", category: "Objects", searchTerms: ["plug", "power", "connect"] },
  { value: "💎", label: "Gem", category: "Objects", searchTerms: ["gem", "diamond", "premium", "valuable"] },
  { value: "🎁", label: "Gift", category: "Objects", searchTerms: ["gift", "present", "release"] },
  { value: "🏆", label: "Trophy", category: "Objects", searchTerms: ["trophy", "win", "award"] },
  { value: "🥇", label: "Gold medal", category: "Objects", searchTerms: ["gold", "first", "medal"] },
  { value: "🥈", label: "Silver medal", category: "Objects", searchTerms: ["silver", "second", "medal"] },
  { value: "🥉", label: "Bronze medal", category: "Objects", searchTerms: ["bronze", "third", "medal"] },
  { value: "🎖️", label: "Honor", category: "Objects", searchTerms: ["medal", "honor"] },
  { value: "🪙", label: "Coin", category: "Objects", searchTerms: ["coin", "money", "credit"] },
  { value: "💰", label: "Money bag", category: "Objects", searchTerms: ["money", "bag", "cost"] },
  { value: "💳", label: "Card", category: "Objects", searchTerms: ["card", "credit", "payment"] },

  { value: "❤️", label: "Heart", category: "Symbols", searchTerms: ["heart", "love", "favorite"] },
  { value: "🧡", label: "Orange heart", category: "Symbols", searchTerms: ["heart", "orange"] },
  { value: "💛", label: "Yellow heart", category: "Symbols", searchTerms: ["heart", "yellow"] },
  { value: "💚", label: "Green heart", category: "Symbols", searchTerms: ["heart", "green"] },
  { value: "💙", label: "Blue heart", category: "Symbols", searchTerms: ["heart", "blue"] },
  { value: "💜", label: "Purple heart", category: "Symbols", searchTerms: ["heart", "purple"] },
  { value: "🖤", label: "Black heart", category: "Symbols", searchTerms: ["heart", "black"] },
  { value: "🤍", label: "White heart", category: "Symbols", searchTerms: ["heart", "white"] },
  { value: "⭐", label: "Star", category: "Symbols", searchTerms: ["star", "favorite", "important"] },
  { value: "🌟", label: "Glowing star", category: "Symbols", searchTerms: ["star", "glow", "shine"] },
  { value: "✴️", label: "Eight star", category: "Symbols", searchTerms: ["star", "eight"] },
  { value: "❇️", label: "Sparkle", category: "Symbols", searchTerms: ["sparkle", "new"] },
  { value: "❓", label: "Question", category: "Symbols", searchTerms: ["question", "help", "ask"] },
  { value: "❗", label: "Exclamation", category: "Symbols", searchTerms: ["exclamation", "alert", "important"] },
  { value: "‼️", label: "Double exclaim", category: "Symbols", searchTerms: ["exclamation", "urgent"] },
  { value: "⁉️", label: "Question exclaim", category: "Symbols", searchTerms: ["question", "exclamation"] },
  { value: "✖️", label: "X", category: "Symbols", searchTerms: ["x", "cross", "no"] },
  { value: "➕", label: "Plus", category: "Symbols", searchTerms: ["plus", "add", "new"] },
  { value: "➖", label: "Minus", category: "Symbols", searchTerms: ["minus", "remove", "subtract"] },
  { value: "➗", label: "Divide", category: "Symbols", searchTerms: ["divide", "division"] },
  { value: "♻️", label: "Recycle", category: "Symbols", searchTerms: ["recycle", "reuse", "refactor"] },
  { value: "🔀", label: "Shuffle", category: "Symbols", searchTerms: ["shuffle", "random", "merge"] },
  { value: "🔂", label: "Repeat one", category: "Symbols", searchTerms: ["repeat", "one"] },
  { value: "🔃", label: "Refresh", category: "Symbols", searchTerms: ["refresh", "reload", "rotate"] },
  { value: "🔄", label: "Sync", category: "Symbols", searchTerms: ["sync", "rotate", "refresh"] },
  { value: "▶️", label: "Play", category: "Symbols", searchTerms: ["play", "start", "go"] },
  { value: "⏸️", label: "Pause", category: "Symbols", searchTerms: ["pause", "stop"] },
  { value: "⏹️", label: "Stop", category: "Symbols", searchTerms: ["stop"] },
  { value: "⏭️", label: "Next", category: "Symbols", searchTerms: ["next", "skip", "forward"] },
  { value: "⏮️", label: "Previous", category: "Symbols", searchTerms: ["previous", "back"] },

  { value: "🌱", label: "Sprout", category: "Nature", searchTerms: ["sprout", "seedling", "new", "grow"] },
  { value: "🌿", label: "Herb", category: "Nature", searchTerms: ["herb", "leaf", "green"] },
  { value: "🍀", label: "Clover", category: "Nature", searchTerms: ["clover", "lucky"] },
  { value: "🌳", label: "Tree", category: "Nature", searchTerms: ["tree", "branch"] },
  { value: "🌲", label: "Evergreen", category: "Nature", searchTerms: ["tree", "evergreen"] },
  { value: "🌴", label: "Palm", category: "Nature", searchTerms: ["palm", "tree", "vacation"] },
  { value: "🌵", label: "Cactus", category: "Nature", searchTerms: ["cactus", "desert"] },
  { value: "🌸", label: "Blossom", category: "Nature", searchTerms: ["blossom", "flower"] },
  { value: "🌻", label: "Sunflower", category: "Nature", searchTerms: ["sunflower", "flower"] },
  { value: "🌷", label: "Tulip", category: "Nature", searchTerms: ["tulip", "flower"] },
  { value: "🌹", label: "Rose", category: "Nature", searchTerms: ["rose", "flower"] },
  { value: "🍃", label: "Leaves", category: "Nature", searchTerms: ["leaves", "wind"] },
  { value: "🍂", label: "Falling leaves", category: "Nature", searchTerms: ["leaves", "autumn"] },
  { value: "🌊", label: "Wave", category: "Nature", searchTerms: ["wave", "ocean", "water"] },
  { value: "🔥", label: "Fire", category: "Nature", searchTerms: ["fire", "hot", "flame"] },
  { value: "💧", label: "Drop", category: "Nature", searchTerms: ["drop", "water"] },
  { value: "❄️", label: "Snowflake", category: "Nature", searchTerms: ["snow", "cold", "freeze"] },
  { value: "☀️", label: "Sun", category: "Nature", searchTerms: ["sun", "sunny", "bright"] },
  { value: "🌙", label: "Moon", category: "Nature", searchTerms: ["moon", "night"] },
  { value: "⭐", label: "Star", category: "Nature", searchTerms: ["star", "night"] },
  { value: "⚡", label: "Lightning", category: "Nature", searchTerms: ["lightning", "fast", "bolt"] },
  { value: "☁️", label: "Cloud", category: "Nature", searchTerms: ["cloud", "weather", "saas"] },

  { value: "⚽", label: "Soccer", category: "Activity", searchTerms: ["soccer", "ball", "football"] },
  { value: "🏀", label: "Basketball", category: "Activity", searchTerms: ["basketball", "ball"] },
  { value: "🎾", label: "Tennis", category: "Activity", searchTerms: ["tennis", "ball"] },
  { value: "🏈", label: "Football", category: "Activity", searchTerms: ["football", "american"] },
  { value: "⚾", label: "Baseball", category: "Activity", searchTerms: ["baseball", "ball"] },
  { value: "🎮", label: "Game", category: "Activity", searchTerms: ["game", "controller", "play"] },
  { value: "🕹️", label: "Joystick", category: "Activity", searchTerms: ["joystick", "game"] },
  { value: "🎲", label: "Dice", category: "Activity", searchTerms: ["dice", "random", "chance"] },
  { value: "🧩", label: "Puzzle", category: "Activity", searchTerms: ["puzzle", "piece", "module"] },
  { value: "🎬", label: "Clapperboard", category: "Activity", searchTerms: ["clapperboard", "movie", "action"] },
  { value: "🎤", label: "Mic", category: "Activity", searchTerms: ["mic", "microphone", "voice"] },
  { value: "🎧", label: "Headphones", category: "Activity", searchTerms: ["headphones", "audio", "listen"] },
  { value: "🎵", label: "Note", category: "Activity", searchTerms: ["note", "music"] },
  { value: "🎶", label: "Notes", category: "Activity", searchTerms: ["notes", "music"] },
  { value: "🎺", label: "Trumpet", category: "Activity", searchTerms: ["trumpet", "music"] },
  { value: "🥁", label: "Drum", category: "Activity", searchTerms: ["drum", "music"] },
  { value: "🎯", label: "Bullseye", category: "Activity", searchTerms: ["bullseye", "target", "goal"] },
  { value: "🪁", label: "Kite", category: "Activity", searchTerms: ["kite", "fly"] },
  { value: "🎈", label: "Balloon", category: "Activity", searchTerms: ["balloon", "celebrate"] },
  { value: "🎉", label: "Party", category: "Activity", searchTerms: ["party", "celebrate", "release"] },
  { value: "🎊", label: "Confetti", category: "Activity", searchTerms: ["confetti", "celebrate"] }
];
